### ISSUE TITLE
Atribuição

### ISSUE THREAD

**Issue by raphaelzamataro** [villares/material-aulas#131]
estudando pelo material [Processing-Python-py5](https://github.com/villares/material-aulas/tree/main/Processing-Python-py5), acho que seria mais interessante uma pequena modificação no código abaixo, pois assim como está descrito o nome 'Guido' estaria sob o retângulo.( como esse é o meu primeiro Issues, peço desculpa antecipadamente caso eu tenha parecido pouco arssertivo.

lado = 50  # cria a variável `lado` que aponta para o valor 50
rect(10, 10, lado, lado)  # desenha um retângulo na posição x:10, y:10, largura:50, altura:50

nome = 'Guido'
text(nome, 20, 20)  # desenha o texto de `nome` na área de desenho

O cógido novo ficaria assim:

lado = 50  # cria a variável `lado` que aponta para o valor 50
rect(10, 10, lado, lado)  # desenha um retângulo na posição x:10, y:10, largura:50, altura:50

nome = 'Guido'
text(nome, 20, 75)  # desenha o texto de `nome` na área de desenho

**Comment by villares** [comment]
Muito obrigado @raphaelzamataro!

Arrumei, aproveitando para testar:

![image](https://user-images.githubusercontent.com/3694604/201803717-ed781aeb-49c0-41a5-b9ce-b12c5945be60.png)

Quando encontrar outros desses problemas pode experimentar editar :pen: e fazer um *Pull Request* se quiser!

Abraços!
