### ISSUE TITLE
Sumário está sobreposto ao texto no celular

### ISSUE THREAD

**Issue by guilhermesv** [villares/material-aulas#133]
No celular ao visualizar algumas páginas com um sumário longo, o sumário acaba ficando sobre o texto como na imagem em anexo.
![2023-11-28 08_51_33-Alexandre Villares — Mozilla Firefox](https://github.com/villares/material-aulas/assets/2853592/2b7196da-0e46-4135-b215-48926288eb26)

Sugestão acrescentar a regra de CSS:

```
@media screen and (max-width: 600px) {
  div.summary-style {
    float: none;
  }
}
```

**Comment by villares** [comment]
Nossa, muito obrigado @guilhermesv! Acho que a sua sugestão matou a pau!
