### ISSUE TITLE
Sugestão: incluir link da página do projeto no repositório

### ISSUE THREAD

**Issue by guilhermesv** [villares/material-aulas#134]
Ao chegar no repositório não encontrei um link para a versão site do conteúdo (https://abav.lugaralgum.com/material-aulas/), não sei a ideia era deixar isso em um segundo plano, mas podia ser interessante ter esse link nas configurações do repositório ou no readme.md inicial.

**Comment by villares** [comment]
Tinha até o lugar certo pra URL do projeto embaixo do About do repositório!
