### ISSUE TITLE
Explicar como carregar uma imagem PNG ou Raster

### ISSUE THREAD

**Issue by brunaturquiai** [villares/material-aulas#19]
Com código exemplo `loadImage()`

**Exemplo:**
def setup():
    size(400, 400)
    global imagem
    imagem = loadImage("image.jpg")

def draw():
    background(255)
    image(imagem, 0, 0)

**OBSERVAÇÕES:**
Arrastar a imagem em JPG para a tela do processing.
Verificar se a imagem está na pasta data (Command + K)
Colocar no lugar de "image.jpg" o nome do arquivo que escolher

**Comment by villares** [comment]
código formatado corretamente com ````python` no começo e ````` no final.

**Exemplo:**
```python
def setup():
    size(400, 400)
    global imagem
    imagem = loadImage("image.jpg")


def draw():
    background(255)
    image(imagem, 0, 0)
```
