### ISSUE TITLE
Demonstrar uso de recursos vetorias em SVG

### ISSUE THREAD

**Issue by PTOSTES** [villares/material-aulas#20]
Código nos exemplos demonstrando `loadShape()`:

```python
def setup():
    size(280, 360)
    global bot
    bot = loadShape("bot1.svg")

def draw():
    background(102)
    shape(bot, 110, 90, 100, 100)
    shape(bot, 280, 40)
```

Requer arquivo `bot1.svg` na pasta `data`.

**Comment by villares** [comment]
https://github.com/villares/material-aulas/blob/master/Processing-Python/recursos_vetoriais_externos.md
