### ISSUE TITLE
Demonstrar ".get()" para obter cor de pixels de uma imagem

### ISSUE THREAD

**Issue by Roberto-bgsilva** [villares/material-aulas#21]
Exemplo:

```python
 def setup():
    size(500,500)
    global imagem
    imagem = loadImage('arquivo.png')
    
 def draw():
    iw, ih = imagem.width, imagem.height
    print(iw, ih)
    cor = imagem.get(mouseX, mouseY)
    fill(cor)
    noStroke()
    image(imagem, 100, 100, 230, 240)
    circle(mouseX, mouseY, 30)
```

**Comment by villares** [comment]
Obrigado @Roberto-bgsilva !

Tinha umas questões de indentação no exemplo, aproveitei para usar ` ``` ` e removi um "background" que não fazia sentido. Me avise se quiser conversar mais sobre esse exemplo!

**Comment by Roberto-bgsilva** [comment]
Valeu!

> Obrigado @Roberto-bgsilva !
> 
> Tinha umas questões de indentação no exemplo, aproveitei para usar `` ``` `` e removi um "background" que não fazia sentido. Me avise se quiser conversar mais sobre esse exemplo!

Valeu!

**Comment by villares** [comment]
Vai ser incorporado em: https://github.com/villares/material-aulas/blob/master/Processing-Python/pixels.md
