### ISSUE TITLE
Importar imagens para o python utilizando como background

### ISSUE THREAD

**Issue by helizabethtrindade** [villares/material-aulas#25]
Existe a possibilidade de inserirmos uma imagem no python para criar um background? 

Ex: Importar uma imagem natalina e coloca-la de fundo.

**Comment by villares** [comment]
Boa Issue! Sim é possível usar uma imagem como fundo.

O passo comum é carregar uma imagem, por exemplo da pasta `data` dentro do seu sketch:

```python
imagem = loadImage("arquivo.png")
```

Se a imagem tiver **exatamente** a mesma dimensão da área de desenho ela pode ser usada em `background()`.

```python
def setup():
    size(600, 400)
    global imagem_fundo
    imagem_fundo = loadImage("fundo.png")  #  fundo tem que ter 600x400 pixels

def draw():
    background(imagem_fundo)
    # outros desenhos sobre o fundo aqui
```

De outra forma pode-se usar simplesmente `image()` para desenhar uma imagem na área de desenho logo no começo do `draw()`.

```python
def setup():
    size(600, 400)
    global imagem_fundo
    imagem_fundo = loadImage("fundo.png")

def draw():
    image(imagem_fundo, 0, 0, width, height)  # vai forçar/distorcer o tamanho na imagem
    # outros desenhos sobre o fundo aqui
```

**Comment by villares** [comment]
pode ser combinada com esta issue: https://github.com/villares/material-aulas/issues/19
