### ISSUE TITLE
Como exportar imagens sem substituir imagens que já foram exportadas anteriormente?

### ISSUE THREAD

**Issue by caioluanc** [villares/material-aulas#26]
No texto [Como exportar uma imagem](https://github.com/villares/material-aulas/blob/master/Processing-Python/exportando_imagem.md), é dito que adicionando caracteres "#" no final do nome do arquivo, ele é salvo com o número do frame. Porém, se já existir um arquivo salvo com esse nome, ele é substituído. Existe alguma maneira de impedir isso?

Eu pensei em adicionar um número randômico no final do nome do arquivo, mas isso não é 100% seguro porque mesmo um número randômico pode se repetir. Outra coisa que eu pensei seria adicionar um código que combine data e hora de criação do frame no final do arquivo.

**Comment by villares** [comment]
Boa issue!

Uma solução legal acho que é o que vocês falaram de data e hora, conhecido também como*date-and-time-stamp*  :)

```python
nome_arquivo = "{}-{}-{}-{}-{}-frame###.png".format(year(),
                                                    month(),
                                                    day(),
                                                    hour(),
                                                    minute(),
                                                    second())
saveFrame(nome_arquivo)
```

**Comment by caioluanc** [comment]
@villares ficou ótimo! Obrigado pela dica
