### ISSUE TITLE
Qual é o comando para a quebra de linhas?

### ISSUE THREAD

**Issue by alinegdc** [villares/material-aulas#27]
Qual seria o comando para a quebra de linha, evitando a repetição do uso do print?

Exemplo:
def setup():
    print('Senhora Aline')
    print('sua fatura vence no dia 01/12')

A minha dúvida está voltada principalmente para parágrafos grandes.

**Comment by villares** [comment]
Obrigado pela issue, Aline!

Em Python é possível usar `\n` no meio da string para obter uma quebra de linha. 

```python
print(u'frutas frescas:\nmaça\nbanana')
```
Resultado:
```
frutas frescas:
maçã
banana
```
O `\` é chamado de 'caractere de escape' permite obter elementos especiais, por meio de uma 'sequencia de escape', como por exemplo uma tabulação (`\t`) ou um sol ☀ (`\u2600`). Se precisar usar a própria barra invertida na string escreva `\\`.

Uma outra maneira de indicar uma string com quebras de linha é com aspas triplas `'''` ou `"""`:
```python
print(
u"""
frutas frescas:
maçã
banana
"""
```
O `u` antes da string é necessário para poder usar caracteres não-ASCII, como letras acentuadas (tem uma explicação disto [aqui](https://github.com/villares/material-aulas/blob/master/Processing-Python/futuro.md)) .
