### ISSUE TITLE
Poderíamos utilizar uma matriz para criar shapes em movimento?

### ISSUE THREAD

**Issue by camilasb** [villares/material-aulas#28]
Alem das alternativas a arrays que foram mostrados em aula, há a possibilidade de utilizar uma matriz para criar shapes em movimento?

**Comment by villares** [comment]
Oi Camila,

Obrigado pelo pergunta! Não sei entendi bem... você tem algo específico em mente?

A resposta em programação quase sempre é 'sim, é possível', resta ver se é conveniente (ou em certos casos ético :D). Tirando a piada, mostrei na aula uma *lista* que é uma estrutura bem parecida mesmo como *array* em outras linguagens (Python também tem *array* mas é menos usado, ele serve para elementos de apenas um tipo definido).

Uma matriz pode ser implementada como um array de duas ou mais dimensões ou ainda, como costumo fazer, uma lista de listas, que se comporta como uma matriz ou array2D.

Aqui tem um exemplo: https://github.com/villares/py.processing-play/blob/3cbf31abec049315c89f49468f4c6a95dbd812ed/cellular_automata/yet_another_CGoL/yet_another_CGoL.pyde

Veja se faz algum sentido este exemplo:

**Comment by camilasb** [comment]
Olá! Sim! era isso q eu pensei, pois em Java eu sei que existe, mas nao sabia se havia algo similar em phyton =)
obrigada!
