### ISSUE TITLE
Acessar links por meio de Imagem

### ISSUE THREAD

**Issue by masilvestrini** [villares/material-aulas#29]
Seria possível inserir um link (de qualquer natureza) no código para que uma pessoa conseguisse clicar na imagem que se forma e acessar o endereço? 

Um exemplo seria um botão em um website para entrar em outra página.

Obrigada :)

Mayara Silvestrini

**Comment by villares** [comment]
Boa Issue Mayara!

Tem nos exemplos que vem no IDE em (`File > Examples...`)
Você procura  `Basic > Web > LinkEmbedding`, o exemplo está semi-quebrado acho.

Mas a sintaxe que 'manda abrir no navegador o link' é esta aqui:
`link("http://www.processing.org")`

**Comment by villares** [comment]
Veja só, como exemplo do modo Python estava desatualizado, eu fiz uma correção e fiz um PR para o mantenedor do projeto:
https://github.com/jdf/processing.py/pull/353

**Comment by masilvestrini** [comment]
Obrigada por responder! :)
