### ISSUE TITLE
É possível traduzir textos com Python?

### ISSUE THREAD

**Issue by smafaldas** [villares/material-aulas#30]
Existe a possibilidade de utilizar o Google Translate utilizando Python?
Em um chat ou texto longo, por exemplo.

Sthefânia Mafalda

**Comment by villares** [comment]
Olá Sthefânia!

Sim é possível de diversas maneiras, talvez a mais simples seja acessando os serviços de tradução do Google Translate via programação.

A interface para usar um serviço via programação é chamada **API**, e usar esse recurso é descrito com o jargão *consumir uma API* que eu acho meio ridículo.

Fui dar uma olhada aqui e é um pouco chato, você precisa se cadastrar (obter credenciais ou as chaves da API) e o exemplo que achei é pra rodar em um servidor: 
https://cloud.google.com/translate/docs/basic/setup-basic

Vou ver se tem um exemplo mais simples.

**Comment by villares** [comment]
Deve dar para usar esta biblioteca aqui: https://code.google.com/archive/p/google-api-translate-java/

**Comment by villares** [comment]
Essa issue é interessante, mas eu vou fechar por conta de falta de tempo para ampliar o material nesta direção :(
