### ISSUE TITLE
Prévia da imagem do código

### ISSUE THREAD

**Issue by Felipexpd** [villares/material-aulas#31]
Como anexar uma imagem junto ao código para ter uma prévia sem precisar inserir o código no processing ?

**Comment by villares** [comment]
Desculpe, acho que não entendi a sua pergunta! Como mostrar uma imagem com o código em qual suporte/contexto?

No GitHub:
Num arquivo 'puro código' isso não é possível (`.pyde` ou `.py`)
Num arquivo 'markdown' (`.md`)  você pode por a imagem com `![nome](url_imagem)` e o código entre ` ```python ` e ` ``` ` para formatar direitinho. 

Exemplo: 
https://github.com/villares/material-aulas/blob/master/Processing-Python/desenho-3D.md
E o código do markdown que você pode ver clicando no botão 'Raw`: https://raw.githubusercontent.com/villares/material-aulas/master/Processing-Python/desenho-3D.md
