### ISSUE TITLE
Como exportar um código interativo para outra plataforma?

### ISSUE THREAD

**Issue by lwschmitt** [villares/material-aulas#32]
Quando criamos um código que depende de intervenção humana para realizar uma interação, é possível exportar esse código como um arquivo que não dependa do processing para ser executável? Tipo um .exe?

**Comment by villares** [comment]
Olá @lwschmitt!

Sim!!! Eu chamo isso informalmente de "empacotar", mas o termo na IDE é esse mesmo que você usou, exportar: `File > Export Application...` (em português acho que fica `Arquivo > Exportar Aplicativo...` confiram pra mim)

E isso gera um executável `.exe` para Windows, ou um aplicativo de Mac OS ou ainda um executável para Linux. 

Se não me engano, para gerar para Mac OS você precisa estar em um Mac. Outra coisa a se conferir é que no modo Python tem dado algumas encrencas em algumas plataformas, precisa dar uma testada.

Existe também um Processing modo Android, com a mesma sintaxe do modo Java, que exporta um `.apk` para instalar em tablets e celulares com Android.

**Comment by villares** [comment]
iniciada a explicação em https://github.com/villares/material-aulas/commit/72b6b1bc83a2683f15227a33187a36b3db31461d
