### ISSUE TITLE
Como trabalhar com som no Processing modo Python?

### ISSUE THREAD

**Issue by bgrandino** [villares/material-aulas#33]
No código os gráficos sofrem influência do movimento do mouse, seria possível que ao invés disso, ao incluir música os gráficos mudarem por  influencia das batidas da música?

```
def setup():
    size(600,600)
    noFill()
    strokeWeight(3)
    colorMode(HSB)

t = 0 #time veriable
NUM_TRIS = 90

def draw():
    global t
    background(0)
    translate(width/2, height/2)
    NUM_TRIS = map(mouseX,0,width,3,120)
    for i in range(int(NUM_TRIS)):
        rotate(radians(360/NUM_TRIS))
        pushMatrix() #save this orientation
        translate(200,0)
        offset= map(mouseY,0,height,1,10)
        rotate(radians(t+offset*i*360/NUM_TRIS))
        stroke(3*i,255,255)
        tri(100)
        popMatrix() #return to saved orientation
    t +=0.5
    
def tri(length):
    '''Draws an equilateral triangle of given
    length around the center of the triangle'''
    triangle(0,-length, -length*sqrt(3)/2,length/2,
             length*sqrt(3)/2,length/2)
```             
    
![1](https://user-images.githubusercontent.com/57465526/70285527-887b1880-17a6-11ea-8037-f697af0968ff.jpg)
`
Código retirado do tutorial:     https://www.youtube.com/watch?v=gLt1cN3CDDY&t=26s

**Comment by villares** [comment]
Sim! 

Para fazer isso é possível usar a biblioteca *Sound* da própria fundação Processing.
Dá tanto para ouvir um arquivo .mp3 como a entrada de áudio (ou microfone) do micro em tempo ral.

Examplo de sketch que reage ao som (precisa baixar a biblioteca Sound no IDE):
https://github.com/villares/sketch-a-day/blob/f4b15d8ac49d12cbd31eff4995addf606de3df3d/2019/sketch_190916b/sketch_190916b.pyde

**Comment by villares** [comment]
Vou começar a escrever alguma coisa nesta página aqui:
https://github.com/villares/material-aulas/blob/master/Processing-Python/audio_in_out.md

- [x ] Reagir ao microfone
- [  ] Produzir som 
   - [  ] Importar e tocar um arquivo/sample de som (mp3 ou outro formato)
   - [ ]  Produzir som sintetizado  
-  [ ] Visualizações / análise da onda sonora

**Comment by villares** [comment]
Com a migração para o py5, eu vou fechar essa issue.

Me interessaria sim mostrar integração com som, mas teria que abrir uma outra issue nova.

Exemplo do sketch-a-day com `pyaudio` https://github.com/villares/sketch-a-day/blob/main/2023/sketch_2023_04_08/sketch_2023_04_08.py

```python
import py5
import pyaudio
import numpy as np

"""Simple Blocking Stream PyAudio"""
CHUNK = 128  # Samples: 1024,  512, 256, 128
RATE = 44100  # Equivalent to Human Hearing at around 40 kHz
INTERVAL = 0.1  # Sampling Interval in Seconds

# If you are having trouble  making sense of the above, this might help:
# CHUNK: How many slices of sound
# RATE: How Fast these slices are captured
# INTERVAL: How much time to listen
# INIT PyAudio Instance
p = pyaudio.PyAudio()
# OPEN/Configure Stream:
stream = p.open(format=pyaudio.paInt16,
                channels=1,
                rate=RATE,
                input=True,
                frames_per_buffer=CHUNK)

def setup():
    py5.size(400, 400)
    py5.no_fill()

def draw():
    py5.background(240)
    sample_size = int(INTERVAL*RATE/CHUNK)
    w = py5.width / sample_size
    for i in range(sample_size):  # STREAN INTERVAL
        data = np.frombuffer(stream.read(CHUNK), dtype=np.int16)
        v = np.amax(data)
        py5.circle(i * w, py5.height / 2, v / 10)
        
def exiting():
    stream.stop_stream()
    stream.close()
    p.terminate()

py5.run_sketch()
```
