### ISSUE TITLE
Como trabalhar com um tela de dimensões variáveis ("design responsivo")

### ISSUE THREAD

**Issue by vdestri** [villares/material-aulas#35]
<<Documentar como redimensionar a tela de desenho e boas práticas de levar em consideração um tamanho variável de tela no código ("design responsivo")>>

**Comment by villares** [comment]
O que você chama de "responsivo"?  Está pensando no contexto de web-design?

Desculpe, esse vocabulário não sentido no contexto deste material de programação criativa.

**Comment by vdestri** [comment]
Não dá pra fazer aquele rolê das bolinhas _quicantes_ de modo que ela se adapte à tela?

**Comment by villares** [comment]
Sim, é possível mudar o tamanho da tela, e se você sempre trabalhar com o desenho pensando nas regras (como quicar as bolinhas) em termos do `width'  e 'height'  da área de desenho, o *sketch* se torna "responsivo", no sentido de se adaptar a tela.

Tem um pouco de documentação sobre isso aqui:
https://github.com/villares/py.processing-play/blob/ad5c9f9c06f7f3e47e3edc1fb1478357da22cbe6/advanced_and_window_stuff/resizable_surface_py/resizable_surface_py.pyde

**Comment by villares** [comment]
Acho que avançamos um pouco nessa issue com a criação desta página aqui:
https://github.com/villares/material-aulas/blob/master/Processing-Python/malandragens_com_size.md

Mas faltaria uma discussão de como desenhar sempre usando valores relativos, sobre tamanho da fonte e como mudar a estratégia de distribuição do texto quando não 'cabe' mais.

**Comment by villares** [comment]
Daria pra fazer exemplos melhores mas, mas acrescentei um exemplo de `window_ratio()` e vou fechar esta issue. 

https://github.com/villares/material-aulas/blob/main/Processing-Python-py5/mais_que_size.md
