### ISSUE TITLE
Interação 3D em projeto de massas.

### ISSUE THREAD

**Issue by ferferri** [villares/material-aulas#37]
É possível através do desenho 3D, eu realizar uma visualização em vídeo percorrendo pelos elementos criados? Uma espécie de vídeo 3D de um projeto de arquitetura por exemplo, formado apenas pelos elementos sólidos, a fim de criar um projeção de projeto de massas a ser construído em função do terreno.

**Comment by villares** [comment]
Olá @ferferri 

Tem uma biblioteca bem bacana que chama [QueasyCam](https://github.com/jrc03c/queasycam), que pode ser instalada pelo IDE do Processing, e permite um deslocamento similar a de um videogame "primeira pessoa". 

O exemplo que vem com a biblioteca é de um labirinto. Seria legal alguém portar para o modo Python o exemplo :)

O percurso é interativo, em tempo real controlado com o teclado e o mouse, não sei se atende o que você  estava pensando (pode-se gravar um vídeo).

Se a ideia é simplesmente gerar um percurso sem interatividade aí tem outras bibliotecas também voltadas para animação.

**Comment by villares** [comment]
Para resolver esta issue: 
- Portar para modo Python um exemplo de navegação 'first person' pode ser o da biblioteca Queasy Cam ou um outro simples qualquer.
- Fazer uma página explicando passo a passo como funciona.

**Comment by villares** [comment]
Vou fechar essa issue pois acho que não vou conseguir por isso no escopo deste material.

Para fazer visualizações interativas de arquitetura, hoje, vários anos depois de aberta esta issue, eu tentaria algo com https://www.ursinaengine.org/
