### ISSUE TITLE
Instruções do download da biblioteca para VideoExport

### ISSUE THREAD

**Issue by joffp019** [villares/material-aulas#53]
Talvez só para deixar mais claro, porque eu no início fiquei um pouco confuso pra fazer essa parte, é assim mesmo?

O lugar do site para baixar o .zip, pra cada OS:
![Captura de Tela 2020-06-11 às 16 27 47](https://user-images.githubusercontent.com/14129524/84430779-98196500-ac00-11ea-83de-7931bdcbcfd0.png)

Também é necessário baixar isso no próprio programa, sim?
![Captura de Tela 2020-06-09 às 17 59 52](https://user-images.githubusercontent.com/14129524/84430494-26d9b200-ac00-11ea-80af-35a7e75bd005.png)

E dizer que o .exe deve ser instalado através do próprio Processing também.

**Comment by villares** [comment]
Brilhante, é isso mesmo. Precisamos explicar isso sim.

**Comment by villares** [comment]
Salve @joffp019 rola fazer esse ajuste lá na página?

**Comment by villares** [comment]
Como migrei pro py5, não vou mais atualizar essa explicação da lib Java VideoExport :(
