### ISSUE TITLE
Explicação sobre copy(), blend() e melhorar explicações de manipulação de pixels

### ISSUE THREAD

**Issue by villares** [villares/material-aulas#54]
### Tá faltando

- copy https://py.processing.org/reference/copy.html
- blend https://py.processing.org/reference/PImage_blend.html

Também:
![image](https://user-images.githubusercontent.com/3694604/85018194-27fc6900-b143-11ea-8bd5-b21e4632c048.png)

**Comment by xTecna** [comment]
Olá!

Posso ajudar a acrescentar explicações sobre o copy() e o blend().
A aula sobre Pixels e imagens já tem explicações sobre a obtenção e manipulação de pixels individualmente, então talvez seria bom colocar essas duas explicações nessa aula?

**Comment by villares** [comment]
Salve @xTecna acho que ia ser muito legal uma explicação sobre `pimage.copy()` sim, manda ver!

**Comment by villares** [comment]
pode ser aqui sim:
https://github.com/villares/material-aulas/blob/main/Processing-Python/imagens_externas.md

**Comment by villares** [comment]
@xTecna resolveu com https://github.com/villares/material-aulas/pull/120, muito obrigado!

Agora preciso portar isso pro py5coding.org...
