### ISSUE TITLE
Atendimento - Perguntas extras 

### ISSUE THREAD

**Issue by fernandavallois** [villares/material-aulas#55]
Oi Alexandre, tudo bem? É a Fernanda.

Desculpa, não sei se é o jeito/canal certo de fazer isso, mas não consegui achar seu e-mail então estou experimentando por aqui. :)

Vou deixar aqui as perguntas que acabei não conseguindo falar com você no nosso atendimento, acredito que possa ser do interesse de outras pessoas também, pois são bem gerais.

Segue:

• Como transportar um programa gerado no processing pra outros ambientes e deixa-los interativos? 
- conseguimos colocar em um site por exemplo?

• Tem algum livro / curso / site bom com matemática básica para programação?
- pergunto isso porque estou longe dessa realidade há muito tempo e sinto que as vezes tenho dificuldade não de entender, mas de tornar mais fluido, coisas básicas, de pertencimento, maior/menor que, variáveis, etc.

• Dá pra escrever com alguma interação dentro das letras? 
- por exemplo, escrevermos um texto no programa e ter algo acontecendo, uma interação/distorção, etc, dentro das letras?

• Fluxos, setas - quais funções usar?
- peguei um projeto de id. visual agora que queria aproveitar para explorar o processing, e ele tem esse conceito de fluxos, setas, etc. Não sei ainda o que vou fazer, mas imagino um conjunto de objetos setas, linhas, bolinhas, não sei que se movam num mesmo fluxo ou até fluxos diferentes. Não sei se tem algumas funções específicas ou páginas que poderia indicar para estudar isso?

• por fim, fiz um pad com alguns códigos que encontrei no seu material que achei difíceis de entender, então seria legal poder falar sobre eles, só o do olho, eu que fiz, mas gostaria que as pupilas acompanhassem o mouse sem obviamente sair da iris. haha. Aqui o link: [editado] https://gist.github.com/villares/7eb6b7c79f67d888dfec2daedee08119

beijos e muito obrigada! <3

**Comment by villares** [comment]
Salve Fernanda!

Vou responder melhor segunda acho... mas já vou começando:
>• Como transportar um programa gerado no processing pra outros ambientes e deixa-los interativos?
Sim! https://github.com/villares/material-aulas/blob/master/Processing-Python/export_application.md
  >  conseguimos colocar em um site por exemplo?
Em princípio não, maaassss, tem este projeto experimental github.com/berinhard/pyp5js

> • Tem algum livro / curso / site bom com matemática básica para programação?
Vou pensar... 

> • Dá pra escrever com alguma interação dentro das letras?
>    por exemplo, escrevermos um texto no programa e ter algo acontecendo, uma interação/distorção, etc, dentro das letras?
Sim, mas acho que vai dar trabalho, usar a biblioteca Geomerative para distorcer uma fonte

>• Fluxos, setas - quais funções usar?
> Peguei um projeto de id. visual agora que queria aproveitar para explorar o processing, e ele tem esse conceito de fluxos, setas, etc. Não sei ainda o que vou fazer, mas imagino um conjunto de objetos setas, linhas, bolinhas, não sei que se movam num mesmo fluxo ou até fluxos diferentes. Não sei se tem algumas funções específicas ou páginas que poderia indicar para estudar isso?
> • por fim, fiz um pad com alguns códigos que encontrei no seu material que achei difíceis de entender, então seria legal poder falar sobre eles, só o do olho, eu que fiz, mas gostaria que as pupilas acompanhassem o mouse sem obviamente sair da iris. haha.

Esses dois últimos melhor marcarmos uma conversa!
Tirei o link do pad pq ele pode ser vandalizado (qualquer um edita) e transformei em um *gist* vou olhar!

**Comment by villares** [comment]
Andei escrevendo lá no pad...

**Comment by fernandavallois** [comment]
Muinnto obrigada <3
