### ISSUE TITLE
Exportando Animações

### ISSUE THREAD

**Issue by fernandavallois** [villares/material-aulas#56]
Oi Alê, tudo bem?

Tive problemas com a exportação de video nessa explicação:
https://abav.lugaralgum.com/material-aulas/Processing-Python/exportar_animacoes#c-biblioteca-video-export

Esse site www.ffmpeg.org te da uma opção de baixar um source code ou uns pacotes e executáveis para os sistemas operacionais. Eu baixei o source e uns pacotes do mac mas vem com uns formatos estranhos e não consigo rodar.

Daí, quando colei o código que estava na página da sua explicação, ele retornou esse erro:
<img width="697" alt="Captura de Tela 2020-06-29 às 17 22 04" src="https://user-images.githubusercontent.com/66391689/86052247-1497aa80-ba2d-11ea-900d-d1487b23a3af.png">

obrigada <3

**Comment by villares** [comment]
Salve Fernanda!

onde está `videoExport.setFrameRate(30)` precisaria ser `video_export.setFramRate(30)`!

**Comment by villares** [comment]
@fernandavallois você pode por gentileza tentar rodar agora ver se eu corrigi?

(eu tinha em algum momento editado para 'melhorar'  o exemplo, acrescentando essa parte de ajustes e quebrei o exemplo por estar usando o nome da variável com o objeto da biblioteca errado...)

**Comment by fernandavallois** [comment]
Oba! rolou sim, obrigada! <3
