### ISSUE TITLE
Explicação Pixels

### ISSUE THREAD

**Issue by fernandavallois** [villares/material-aulas#57]
Oi Alem tudo bem?
Desculpa estou a louca dos issues rs

Fui ler esse daqui:
https://abav.lugaralgum.com/material-aulas/Processing-Python/pixels.html

E tem dois códigos que não rodaram aqui e retornaram o mesmo erro, dizendo que estava faltando algo na sintaxe mas não consegui descobrir o que:

<img width="694" alt="Captura de Tela 2020-06-29 às 18 19 49" src="https://user-images.githubusercontent.com/66391689/86060391-00f34080-ba3b-11ea-96a1-0720e110f516.png">

Os dois códigos que apresentação esse erro estão nessa parte:

[aqui](https://abav.lugaralgum.com/material-aulas/Processing-Python/pixels.html#manipulando-individualmente-os-pixels-de-uma-imagem)

**Comment by villares** [comment]
Muito obrigado @fernandavallois ! Vou ter que melhorar bem essa página!
Ela estava incompleta... repare que ela  não está no sumário principal do material... eu não tinha terminado de traduzir os exemplos :rofl: 

Arrumei de inversão mas o  exemplo de pixel sorting eu não consegui arrumar e preciso ver como resolvo.

**Comment by fernandavallois** [comment]
Valeu Ale! ;)

**Comment by villares** [comment]
@fernandavallois confere pra mim se ficou ok a página! se tiver problemas ainda reabrimos a issue!
