### ISSUE TITLE
CadQuery e outras opções de introdução à prog. com Python para Designers e Arquitetes

### ISSUE THREAD

**Issue by feromes** [villares/material-aulas#74]
O CadQuery (https://github.com/CadQuery/cadquery) não seria uma lib interessante para introduzir o pessoal do design de produto e da arquitetura para a programação em Python? Eu confesso que até gosto mais do OpenScad, mas o paradigma funcional pode não servir muito para a realidade que o aluno vai enfrentar adiante.

Que tal desenvolvermos um material para rodar diretamente no Binder ou no Google Colab? Desse modo o aluno não necessita se preocupar com o ambiente de desenvolvimento

Por último, depois do aprendizado básico sobre programação, o aluno fica mais livre para conhecer outras libs e recursos em Python que tenham haver com seu repertório e interesses. Pensei até em algo pragmático como a criação de um mobiliário paramétrico, com geração de corte para CNC/Laser.

Que tal @villares ?

**Comment by villares** [comment]
Salve Fernando!

Tou de olho sim no CadQuery! Tanto na opção em um Binder/Jupyter Notebook como no CQ-editor. mas ainda não consegui fazer ficar tão acessível e interativo quanto eu gostaria... Vamos marcar um bate-papo sobre isso! A tendência é este repositório virar multi-ferramentas.

Para o nosso radar:
- Thonny.org (um IDE que já vem com Python 3) vs. miniconda e possivelmente spyder
- https://github.com/p5py/p5 (já dá pra começar a usar... é Python 3, tem a questão da instalação)
- https://github.com/plasm-language/pyplasm
- SolidPython (gera OpenSCAD) mas não é tão simples o workflow
- Blender (tou achando a interface de rodar os scripts pouco acessível)
- FreeCAD (preciso tempo pra investigar)
- Flat (roda muito legal nos Jupyter notebooks, com widgets, mas não tem 3D viável)

**Comment by villares** [comment]
Por enquanto as opções estão sendo documentadas aqui: https://github.com/villares/Resources-for-teaching-programming/?tab=readme-ov-file#more-floss--python-options-to-explore

e aqui: https://github.com/villares/material-aulas/tree/main/outras-ferramentas
