### ISSUE TITLE
Conteúdo sobre abstrações em programação

### ISSUE THREAD

**Issue by pedro-hga** [villares/material-aulas#75]
O tema surgiu em aula durante algumas dúvidas, e acredito que seia deveras interessante aprofundar sobre esse assunto que, como evidenciado em aula, é essencial para lidar com diversas aplicações do python e programação visual.

Obrigado :)

**Comment by villares** [comment]
Salve @3por5, obrigado pela issue!

Abstração é  uma ideia que transcende uma linguagem de programação e é muito relevante na computação assim com em outras áreas do conhecimento. Veja se faz sentido esta resposta aqui sobre abstração no contexto da programação: 
https://stackoverflow.com/a/21220945

Vou tentar escrever algo inspirado nisso. Outras ideias gerais me parecem ser importantes: generalização e encapsulamento

**Comment by villares** [comment]
Escrevei um pouco em https://github.com/villares/material-aulas/blob/main/Processing-Python-py5/funcoes_py.md e vou fechar aqui.
