### ISSUE TITLE
Criar exemplo de instalação e uso de outras ferramentas (p5py, pyp5js e etc.)

### ISSUE THREAD

**Issue by villares** [villares/material-aulas#77]
Vamos criar páginas ensinado os primeiros passos de outras alternativas ao Processing modo Python:
Opções fora do ecossistema Processing? Como seria um "hello world" no Blender ou no FreeCAD?
ref: https://github.com/villares/material-aulas/issues/74

- [x] **prioridade** py5 http://py5.ixora.io
- [x] p5py https://github.com/p5py/p5   
      -> aqui https://github.com/villares/material-aulas/blob/master/p5py/instalacao_p5py.md
- [ ] pyp5js http://github.com/berinhard/pyp5js
- [ ] [shoebot](https://github.com/shoebot/shoebot/)
- [ ] flat (+ Jupyter/Binder?)
- [x] freeCAD (cc @yorikvanhavre
- [x] Blender (cc @chicortiz)
- [ ] cadQuery
- [ ] [pero](https://github.com/xxao/pero)

**Comment by sedir** [comment]
Para manter como referência, existe a documentação do P5 que mostra como instalar em todas as plataformas https://p5.readthedocs.io/en/latest/install.html

**Comment by chicortiz** [comment]
> Vamos criar páginas ensinado os primeiros passos de outras alternativas ao Processing modo Python:
> 
>     * [x]  p5py https://github.com/p5py/p5
>       -> aqui https://github.com/villares/material-aulas/blob/master/p5py/instalacao_p5py.md
> 
>     * [ ]  pyp5js [http://github.com/berinhard/pyp5j](https://github.com/berinhard/pyp5j)
> 
> 
> Opções fora do ecossistema Processing? Como seria um "hello world" no Blender ou no FreeCAD?
> ref: #74
> 
>     * [ ]  flat (+ Jupyter/Binder?)
> 
>     * [ ]  freeCAD
> 
>     * [ ]  Blender
> 
>     * [ ]  cadQuery

Olá Alê o seguinte link está quebrado:  pyp5js http://github.com/berinhard/pyp5j

**Comment by villares** [comment]
@chicortiz você consegue descrever os passos para um 'hello world' com Python dentro do Blender?

**Comment by chicortiz** [comment]
Oi Alê tudo bem?

Vamos ver se consigo, vou tentar aqui. :)

Um abração!

ChicO

Em dom., 4 de abr. de 2021 às 10:47, Alexandre B A Villares <
***@***.***> escreveu:

**Comment by chicortiz** [comment]
Oi Alê, só para te dar um retorno, estou avançando com este seu pedido.
Acho que hoje cheguei a um esqueleto que faz um certo sentido, consegui dar
uma delimitada.

Abração,

ChicO

Em dom., 4 de abr. de 2021 às 10:47, Alexandre B A Villares <
***@***.***> escreveu:

**Comment by chicortiz** [comment]
Oi Alê! 

Finalmente terminei, desculpe a demora acabou ficando mais extenso do que eu pensei... Creio que ainda tem uma margem enorme para melhorar, é o meu jeito meio tortuoso de entender esta parte que com certeza não é a minha mais forte. O inglês tá fraco, é do google tradutor. Não sei quanto aos termos que usei também se estão precisos... Enfim é alguém que trabalha predominantemente com interface gráfica tentando explicar alguma coisa de "código" ficou uma salada... Agora onde põe isso aqui no github eu não sei...

https://repositoryb.blogspot.com/2021/04/pequeno-guia-blender-python-para.html

**Comment by chicortiz** [comment]
> @chicortiz você consegue descrever os passos para um 'hello world' com Python dentro do Blender?

Oi Alê!

Finalmente terminei, desculpe a demora acabou ficando mais extenso do que eu pensei... Creio que ainda tem uma margem enorme para melhorar, é o meu jeito meio tortuoso de entender esta parte que com certeza não é a minha mais forte. O inglês tá fraco, é do google tradutor. Não sei quanto aos termos que usei também se estão precisos... Enfim é alguém que trabalha predominantemente com interface gráfica tentando explicar alguma coisa de "código" ficou uma salada... Agora onde põe isso aqui no github eu não sei...

https://repositoryb.blogspot.com/2021/04/pequeno-guia-blender-python-para.html

**Comment by yorikvanhavre** [comment]
Desculpem o vacilo aqui pessoal! Aqui está um para o FreeCAD: https://gist.github.com/yorikvanhavre/52d8f755ba5c475099aaff6c59ec497c

**Comment by chicortiz** [comment]
Opa Valeu Y! :) 

Agora é tentar passar isso para cá no GitHub que nem você fez ;)

**Comment by villares** [comment]
Valeu @yorikvanhavre, em tempo para o nosso papo hoje :D

@Chicortiz, muito legal, preciso pensar como vou incluir esse material no repositório, pode ser via link quem sabe...

Preciso pensar num ponto de entrada legal para esses materiais!

**Comment by yorikvanhavre** [comment]
@chicortiz se for markdown, crie um gist em https://gist.github.com e copie/cole.. se for html, deve ter como converter (pandoc talvez?) @villares posso por em um repo se quiser. sim, ta marcado!

**Comment by chicortiz** [comment]
> @chicortiz se for markdown, crie um gist em https://gist.github.com e copie/cole.. se for html, deve ter como converter (pandoc talvez?) @villares posso por em um repo se quiser. sim, ta marcado!

Aaaah! Y! Este "Raw" do seu markdown é ouro, vou usa-lo como base para criar o tal "gist", mais uma vez super obrigado, aprendo tanto com vocês! :)

**Comment by chicortiz** [comment]
Adicionei ao tutorial link da incrível live de Eduardo Medeiros no YouTube:

https://youtu.be/LIvLEmMYyX4

https://repositoryb.blogspot.com/2021/04/pequeno-guia-blender-python-para.html

**Comment by villares** [comment]
Vou encerrar esta issue e voltarei aqui quando conseguir fazer variantes deste material baseadas em outras ferramentas como sugerido pelo Fernando em https://github.com/villares/material-aulas/issues/74
