### ISSUE TITLE
Explicação e  exemplos de cor em outros "formatos" além do RGB 

### ISSUE THREAD

**Issue by alicepires** [villares/material-aulas#80]
- Compatibilização de código de cor em RGB / Pantone / CMYK / outro
 - Comado para indicar que irá usar uma cor não em RGB
 - Transparência : É possível? Como manipular?

**Comment by villares** [comment]
Salve @alicepires, obrigado pela issue!

A primeira parte é muito tensa, não tem um suporte muito legal paa CMYK no Processing. O que não me desanima muito pois as saídas digitais modernas (impressoras de "fine art" inclusive) aceitam RGB. Dá pra exportar camadas para usar "cores especiais" e ainda abrir o resultado exportado em outro programa para refazer a separação de cores.

Mas quanto à segunda parte, dá para usar HSB (matiz saturaçaõ e brilho) e tem transparência ("alpha") e isto está explicado em https://github.com/villares/material-aulas/blob/master/Processing-Python/mais_sobre_cores.md - veja se você sente falta de algo mais nessa página...

Mais pra frente no material sobre manipular pixels eu acho que comento sobre obter novamente os componentes de uma cor já "montada".

**Comment by villares** [comment]
@alicepires me avise se o material ainda não atender (CMYK eu vou ficar devendo mesmo :( )
