### ISSUE TITLE
Lembretes de erros comuns na exportação de PDF

### ISSUE THREAD

**Issue by Deise1990** [villares/material-aulas#84]
Em exportando PDF ter um lembrete sobre algumas situações de erros que os usuários iniciantes possam cometer que impossibilite a criação do PDF, como se atentar a colocação correta do background..

Muito Obrigada professor pelas aulas!

**Comment by villares** [comment]
Obrigado pela issue @Deise1990 !

Vamos criar uma sessão: "o que pode dar errado?" podemos começar com essa página de exportação de PDF e depois usar esse formato em outras sessões também :D

Veja se estamo esquecendo algo sobre exportação de PDF:
- pense com cuidado se seu sketch precisa salvar apenas um frame ou acumular frames (muda a estratégia um pouco)
- não esqueça que só aparecem na gravação ações e ajustes feitos depois do beginRecord() ou beginRaw() e isso é bastante crítico em relação a:
    - background()
    - ajustes como colorMode(), rectMode() ou outros ajustes de atributos
- não esqueça de declarar com `global` o flag/indicador tanto no draw() como no keyPressed(), se apropriado, para alterar o estado ou início da gravação.

**Comment by villares** [comment]
Será que faltou alguma coisa importante @Deise1990? Posso acrescentar isso e fechar a issue?

> * pense com cuidado se seu sketch precisa salvar apenas um frame ou acumular frames (muda a estratégia um pouco)
> * não esqueça que só aparecem na gravação ações e ajustes feitos depois do beginRecord() ou beginRaw() e isso é bastante crítico em relação a:
>   
>   * background()
>   * ajustes como colorMode(), rectMode() ou outros ajustes de atributos
> * não esqueça de declarar com `global` o flag/indicador tanto no draw() como no keyPressed(), se apropriado, para alterar o estado ou início da gravação.

**Comment by Deise1990** [comment]
Sim, professor!
Me desculpa achei que já tinha respondido!
Muito obrigada!

**Comment by villares** [comment]
Muito obrigado @Deise1990 acho que ficou legal :)
https://github.com/villares/material-aulas/blob/main/Processing-Python/exportando_pdf.md
