### ISSUE TITLE
Sobre a linha "-*- coding: utf-8 -*-"

### ISSUE THREAD

**Issue by ArqErickGabriel** [villares/material-aulas#85]
Me apaixonei pelo modo turtle no Python, e quando vi o conteúdo sobre caneta automática para processing inspirado no turtle do LOGO, e reproduzi fielmente o conteúdo inserido no https://github.com/villares/material-aulas/tree/master/caneta_automatica . Na ocasião, entrei em conflito exatamente nesta linha -*- coding: utf-8 -*-, seguindo todos os passos, criando o caneta_automatica.py, até inclusive baixando os arquivos de exemplo na própria página, porém esse conflito continuou. Existe alguma condição, ou algo a mais que seja necessário para que essa linha de coding funcione?

**Comment by villares** [comment]
Salve @ArqErickGabriel, muito obrigado pela issue!

 O código completo está aqui: https://raw.githubusercontent.com/villares/material-aulas/master/caneta_automatica/caneta_automatica.py

Repare que tem um `#` no começo da linha, ela é  um "comentário especial".
![image](https://user-images.githubusercontent.com/3694604/99703376-ccc5fe00-2a75-11eb-9fe8-699045d7d1b9.png)

Veja se esta explicação aqui te ajuda:
https://github.com/villares/material-aulas/blob/master/Processing-Python/modulos.md

Aguardo a sua resposta! (E sugestão de como podemos melhorar essa documentação!)

**Comment by villares** [comment]
Mudei a linha no comentário, veja se melhorou:
```python
# -*- coding: utf-8 -*-
# Precisa a linha acima exatamente asssim, não remova o '#'!
```
