### ISSUE TITLE
Versionamentos

### ISSUE THREAD

**Issue by ArmandoBM** [villares/material-aulas#86]
Prezado Alexandre,

Gostaria de sugerir um novo conteúdo, abordando o uso do versionamento e git. Poderia ser integrado com a ideia de entregas semanais, que seriam partes do programa final.  Acredito na importância desse tema dado o direcionamento aos ambientes de colaboração no desenvolvimento de software.

**Comment by villares** [comment]
Muito legal a sua sugestão Armando! 

Concordo plenamente com a importância do tema. Você consegue me ajudar a pensar nesse material?

- Uma preocupação: o git na linha de comando me parece muito intimidador para quem está começando.
- Sinto que o desktop.github.com pode fazer uma ponte lega dol controle de versão (e o elemento de colaboração na interface web do GitHub) o que você acha?

**Comment by ArmandoBM** [comment]
Oi professor! Desculpe a demora.
Concorda que por linha de comando... Vamos dizer que o Git não tem muito misericórdia! Agora usar o desktop é ótimo! Vou ver se encontro materiais sobre controle de versão para compartilhar!

**Comment by villares** [comment]
Confere umas referências que o pessoal foi acrescentando nesta página aqui: https://github.com/villares/material-aulas/blob/master/sobre/como-contribuir.md ...

**Comment by villares** [comment]
Salve @ArmandoBM! Imagino que as coisas não tão fáceis por aí também, se quiser conversar sobre esta issue me avise!

**Comment by villares** [comment]
Apesar deu achar que dava pra ter mais material sobre o assunto, vou fechar esta issue. Tem um pouco de informações em https://github.com/villares/material-aulas/blob/master/sobre/como-contribuir.md
e muito mais foge do escopo de ensinar os primeiros passos de programação!
