### ISSUE TITLE
Pequenas correções de erros de digitação

### ISSUE THREAD

**Issue by giovane-93** [villares/material-aulas#89]
Durantes as semanas de aula, ao ler os textos pedidos, notei alguns errinhos de digitação no material-aula, e acabei separando-os para que sejam corrigidos futuramente.

-A palavra "**acomparação**" no link: https://github.com/villares/material-aulas/blob/master/Processing-Python/condicionais_py.md
![correção 1](https://user-images.githubusercontent.com/74790704/99848739-10ddff00-2b59-11eb-8967-9cbc05454801.jpg)

-A palavra "**superioe**" no link: https://github.com/villares/material-aulas/blob/master/Processing-Python/transformacoes_coordenadas.md
![correção 2](https://user-images.githubusercontent.com/74790704/99849202-ea6c9380-2b59-11eb-95a4-9c6fdf6e420e.jpg)

-A palavra "**metado**" no link: https://github.com/villares/material-aulas/blob/master/Processing-Python/transformacoes_coordenadas.md
![correção 3](https://user-images.githubusercontent.com/74790704/99849222-f3f5fb80-2b59-11eb-8cfc-f3deb08a7506.jpg)

-A palavra "**vhama**" no link: https://github.com/villares/material-aulas/blob/master/Processing-Python/transformacoes_coordenadas.md
![correção 4](https://user-images.githubusercontent.com/74790704/99849234-f9ebdc80-2b59-11eb-87fd-a8cd77b831e3.jpg)

-A palavra "**contrução**" no link: https://github.com/villares/material-aulas/blob/master/Processing-Python/mais_sequencias.md
![correção 5](https://user-images.githubusercontent.com/74790704/99849245-feb09080-2b59-11eb-94f1-729b83feb056.jpg)

-A palavra "**deternísticos**" no link: https://github.com/villares/material-aulas/blob/master/Processing-Python/noise.md
![correção 6](https://user-images.githubusercontent.com/74790704/99849259-02dcae00-2b5a-11eb-9355-10c20d8ebb2e.jpg)

Espero ter contribuído um pouco com o material!

Giovane Frade Inocencio

**Comment by villares** [comment]
Salve @giovane-93 ! Muito boa contribuição! 

Posso fazer os ajustes, mas se você animar, pode fazer o seguinte, tentar editar o texto, isso vai gerar um fork, uma cópia do repositório na sua conta do GitHub, aí você faz as modificações, e cria um "Pull Request"  quer tentar?

Abraços!

**Comment by giovane-93** [comment]
Boa tarde Prof. Alexandre,

Fiz as modificações e criei as "pull requests", espero que corretamente hahaha.

Abraço!

**Comment by villares** [comment]
Brilhante contribuição! Obrigada

Esta issue foi resolvida por:
https://github.com/villares/material-aulas/pull/94
https://github.com/villares/material-aulas/pull/93
https://github.com/villares/material-aulas/pull/92
https://github.com/villares/material-aulas/pull/91
